// flow-typed signature: 8d292af8c47b00486208c6bc9900fb02
// flow-typed version: <<STUB>>/bulma_v^0.6.2/flow_v0.65.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'bulma'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'bulma' {
  declare module.exports: any;
}
